matrix:
  TARGET:
    - httpd-php
    - httpd-php-dev
    - httpd-php-full

pipeline:
  # Build and push tags :
  build-and-push:
    image: plugins/docker
    repo: fpfis/${TARGET}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    tags:
      - ${DRONE_TAG}
      - ${DRONE_TAG%%-*}
      - ${DRONE_BRANCH##*/}
    when:
      event: tag


  # Build and push release
  build-and-push-branch:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: ${DRONE_BRANCH##*/}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    target: ${TARGET}
    when:
      event: push
      branch: release/*

  # Mark production
  build-and-push-production:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: production-${DRONE_BRANCH##*/}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      event: push
      branch: production/*
