matrix:
  include:
    - PHP_VERSION: 7.2
      TARGET: httpd-php
    - PHP_VERSION: 7.2
      TARGET: httpd-php-dev
      OCI8_VERSION: 2.1.8
    - PHP_VERSION: 7.2
      OCI8_VERSION: 2.1.8
      TARGET: httpd-php-full
    - PHP_VERSION: 7.1
      TARGET: httpd-php
    - PHP_VERSION: 7.1
      TARGET: httpd-php-dev
      OCI8_VERSION: 2.1.8
    - PHP_VERSION: 7.1
      OCI8_VERSION: 2.1.8
      TARGET: httpd-php-full
    - PHP_VERSION: 5.6
      TARGET: httpd-php
    - PHP_VERSION: 5.6
      TARGET: httpd-php-dev
      OCI8_VERSION: 2.0.12
    - PHP_VERSION: 5.6
      OCI8_VERSION: 2.0.12
      TARGET: httpd-php-full


pipeline:
  # Build and push release
  build-and-push-branch:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: ${PHP_VERSION}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    target: ${TARGET}
    build_args:
      - php_version=${PHP_VERSION}
      - oci8_version=${OCI8_VERSION}
    when:
      event: push
      branch: develop

  # Mark production
  build-and-push-production:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: production-${PHP_VERSION}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
      - php_version=${PHP_VERSION}
      - oci8_version=${OCI8_VERSION}
    when:
      event: push
      branch: master

  # Mark production
  build-and-push-tag:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: [ ${PHP_VERSION}, ${DRONE_TAG%.*}, ${DRONE_TAG} ]
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
    - php_version=${PHP_VERSION}
    - oci8_version=${OCI8_VERSION}
    when:
      event: tag
      matrix:
        PHP_VERSION: ${DRONE_TAG%.*}