matrix:
  include:
    - PHP_VERSION: 7.3
      TARGET: httpd-php
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.3
      TARGET: httpd-php-ci
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.3
      TARGET: httpd-php-dev
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.3
      TARGET: httpd-php-full
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.3
      TARGET: httpd-php-oci
      OCI8_VERSION: 2.2.0
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.3
      TARGET: httpd-php-oci-dev
      OCI8_VERSION: 2.2.0
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php-ci
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php-dev
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php-full
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php-oci
      OCI8_VERSION: 2.1.8
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.2
      TARGET: httpd-php-oci-dev
      OCI8_VERSION: 2.1.8
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php-ci
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php-dev
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php-full
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php-oci
      OCI8_VERSION: 2.1.8
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 7.1
      TARGET: httpd-php-oci-dev
      OCI8_VERSION: 2.1.8
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php-ci
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php-dev
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php-full
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php-oci
      OCI8_VERSION: 2.0.12
      COMPOSER_VERSION: 1.9.3
    - PHP_VERSION: 5.6
      TARGET: httpd-php-oci-dev
      OCI8_VERSION: 2.0.12
      COMPOSER_VERSION: 1.9.3


pipeline:
  # Build and push release
  build-and-push-branch:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: ${PHP_VERSION}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    target: ${TARGET}
    build_args:
      - php_version=${PHP_VERSION}
      - oci8_version=${OCI8_VERSION}
      - composer_version=${COMPOSER_VERSION}
    when:
      event: push
      branch: develop

  # Mark production
  build-and-push-production:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: production-${PHP_VERSION}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
      - php_version=${PHP_VERSION}
      - oci8_version=${OCI8_VERSION}
      - composer_version=${COMPOSER_VERSION}
    when:
      event: push
      branch: master

  # Mark production
  build-and-push-tag:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags:
    - ${PHP_VERSION}
    - ${DRONE_TAG%-*}
    - ${DRONE_TAG}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
    - php_version=${PHP_VERSION}
    - oci8_version=${OCI8_VERSION}
    - composer_version=${COMPOSER_VERSION}
    when:
      event: tag
      matrix:
        PHP_VERSION: ${DRONE_TAG%.*}