matrix:
  PHP_VERSION:
    - 5.6
    - 7.1
  TARGET:
    - httpd-php
    - httpd-php-dev

pipeline:
  # Build and push tags :
  build-and-push:
    image: plugins/docker
    repo: fpfis/${TARGET}
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
      - php_version=${PHP_VERSION}
    tags:
      - ${DRONE_TAG}-ubuntu
      - ${DRONE_TAG%%-*}-ubuntu
      - ${PHP_VERSION}-ubuntu
    when:
      event: tag

  # Build and push release
  build-and-push-branch:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: ${PHP_VERSION}-ubuntu
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    target: ${TARGET}
    build_args:
      - php_version=${PHP_VERSION}
    when:
      event: push
      branch: release/*

  # Mark production
  build-and-push-production:
    image: plugins/docker
    repo: fpfis/${TARGET}
    tags: production-${PHP_VERSION}-ubuntu
    target: ${TARGET}
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    build_args:
      - php_version=${PHP_VERSION}
    when:
      event: push
      branch: production/*
