workspace:
  base: /fpfis/
  path: httpd-php

pipeline:
  build-and-push-image:
    image: plugins/docker
    repo: fpfis/httpd-php
    tags:
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: release/*
